language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
before_install: gem install bundler -v '~> 1.17'
gemfile:
- gemfiles/sidekiq3.gemfile
- gemfiles/sidekiq4.gemfile
- gemfiles/sidekiq5.gemfile
deploy:
  provider: rubygems
  api_key:
    secure: HQ8O6JFLXqs91LFfAkwQyk3NGJ6EAvTrlS1IHGZrU8qHz+4or7VQJEAtwhimy7Za2Kylhr5t1oIK/D+9Ko8YmSZzVKtFoMwQLEQizNjt1zmkcrVsGVBewm8Dp6e9eEceYap0zm/LSMRog7ePicDUbkfg3eoZxuWPSd3L5AuQ73VydDL9WFTiv1ilCdx+DQAZ5D7NjfP6//FlP3QHHAu+SLj1vz3ejB6FgJndrKB45FEYnKH0J0jcnuTHjcrHxURmzot1+MSi322bLdQLY/I1t7GAdyGEvv+5GdCZn8PyCbK9Z3YktBXMGG/oILxhoUvTrWbrJzce6TlijywekXUU3uljJOW7gvLAYDaHSKO249YyvvjZrFwbqaBS+SFFRfeNnYOkiZjQAN+3t4QHLd4OOTPMiUagIAJqjrMwS56HQxoPUz+4gJ0mTvMG9VO1WZgbDyFqYyoiQZbtOoc8p4uDdhq3pbDR2cA4PfVOLGDDrkaKb5rqzrjuDfWNleTgIst2ON+xfMJy/uvvBLvcWAkYLwNNvhJn2tn01Zuaj+DMzk5+KU6tSmtSgfvAh/DmTHZDrMKuyGDgSUomicAbUVR9U6/+r4EHMuwvXs2UpSH+0oIxxJIdjb2T55yAid2XrI3fbzvnoReT21UkPWAnrjlUXZ/XFfjCrhS+NxNjZOUMuns=
  gem: sidekiq-logstash
  on:
    tags: true
    repo: iMacTia/sidekiq-logstash
    rvm: 2.6

